version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y dos2unix
  pre_build:
    commands:
      - echo Pre-build phase started...
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/FreshNet.jar
  discard-paths: yes
cache:
  paths:
    - /root/.m2/**/*
